apiVersion: v1
kind: Secret
metadata:
  name: {{ include "athena.fullname" . }}
  labels:
    {{- include "athena.labels" . | nindent 4 }}
type: Opaque
stringData:
  aap2-password: {{ .Values.aap2.password | quote }}
  kira-api-key: {{ .Values.kira.apiKey | quote }}
  rocketchat-auth-token: {{ .Values.rocketchat.apiAuthToken | quote }}
  maas-virtual-key: {{ .Values.maas.virtualKey | quote }}
  {{- if .Values.tavily.apiKey }}
  tavily-api-key: {{ .Values.tavily.apiKey | quote }}
  {{- end }}
